### ISSUE TITLE
Add Fonts and Hex Codes used to the README

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/assets#103]
I will get round to this ASAP...

For color reference:

- Brown: `#492c14` http://www.color-hex.com/color/492c14
- Green: `#006400` http://www.color-hex.com/color/006400

Fonts:

- Logo: `SaxMono` http://www.dafont.com/saxmono.font
- Other: `Monaco`

**Comment by erictleung** [comment]
For color reference:

- Brown: `#492c14` http://www.color-hex.com/color/492c14
- Green: `#006400` http://www.color-hex.com/color/006400
