### ISSUE TITLE
Stylized Quote: "Talk is cheap. Show me the code"

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#108]
Quote: "Talk is cheap. Show me the code"
Quotee: Linus Torvalds

Requirements: 
- vector graphic
- monochromatic
- iconography is OK
- dimensions should be 4:3

Here are some examples of relatively conventional typographic quotes you would see on t-shirts: 

![](http://assets.yellowtrace.com.au/wp-content/uploads/2013/05/Typography-Posters-of-Inspirational-Quotes-by-Ben-Fearnley-Yellowtrace-02.jpg)

![](http://cdn.shopify.com/s/files/1/0166/0736/products/Screen_Shot_2014-04-06_at_5.57.13_PM_large.png?v=1435811856)

**Comment by amitbhandari** [comment]
![code](https://cloud.githubusercontent.com/assets/14908745/19213007/d577fe84-8d7d-11e6-88a3-546627066d39.jpg)

watch this

**Comment by atjonathan** [comment]
@amitbhandari, is it possible to make the word, `is`, slightly more legible? Other than that, I like this design! I'm not sure about the hyphen before `Linus Torvalds` but i'll leave that up to @QuincyLarson 😄 

cc @QuincyLarson

**Comment by QuincyLarson** [comment]
@amitbhandari This is a good start. Do you have any type faces that better communicate cheapness? Also, the typeface you use for "the code" doesn't evoke code for me.

Finally, keep in mind that this will be on a t-shirt so the fonts should be thicker (so they'll stand up to repeat washings better). Also, I don't think we need the attribution in the design itself. 

Here's an example of one of these that was well received: ![](https://i.imgur.com/nlupFKM.jpg)

**Comment by amitbhandari** [comment]
![code-2](https://cloud.githubusercontent.com/assets/14908745/19218729/1b33b9a8-8e1f-11e6-86d0-72dc5473cadd.jpg)

**Comment by QuincyLarson** [comment]
@amitbhandari Hm... this is looking very similar to the "it's all talk until the code runs" design. Would you be interested in tackling one of the other typographic quotes, first?

**Comment by DragonVirus** [comment]
I happen to have a design for this i made for myself but haven't printed yet. 
![talkischeaptshirtpreview](https://cloud.githubusercontent.com/assets/1311765/19696859/f4355d32-9b0e-11e6-87b6-f3f8a1c612d5.jpg)

**Comment by QuincyLarson** [comment]
@DragonVirus my subjective impression is that this design is too literal. I'm skeptical that members of our community would pay for this and wear it. Do you have any other ideas for how you could execute this design?

**Comment by racketINK** [comment]
I thought about this and simply sketched (first draft).  I googled images, as reference, of angrybird chirping / cheap / yoda (outfit and thought process) / chalk board (from googling "show me") w/ written code (also code of 0's and 1's on the birds face).  

Further art direction would help...


![img_20170117_132811](https://cloud.githubusercontent.com/assets/789404/22035102/b198d3e2-dcbc-11e6-9758-56429ab1effc.jpg)

More of my sketches on instagram:

**Comment by QuincyLarson** [comment]
@racketINK thanks for sharing your idea. We hope to have something much simpler with an emphasis on the words themselves, like in the example images I shared.
