### ISSUE TITLE
Stylized Quote: "It's all talk until the code runs."

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/assets#111]
Quote: "It's all talk until the code runs."
Quotee: Ward Cunningham

Requirements:
- vector graphic
- monochromatic
- iconography is OK
- dimensions should be 4:3

Here are some examples of relatively conventional typographic quotes you would see on t-shirts: 

![](http://assets.yellowtrace.com.au/wp-content/uploads/2013/05/Typography-Posters-of-Inspirational-Quotes-by-Ben-Fearnley-Yellowtrace-02.jpg)

![](http://cdn.shopify.com/s/files/1/0166/0736/products/Screen_Shot_2014-04-06_at_5.57.13_PM_large.png?v=1435811856)

**Comment by kosta-xd** [comment]
![fcc-quote itsalltalk](https://cloud.githubusercontent.com/assets/16733970/17850896/9e331f82-685f-11e6-9efb-93afd921cffe.jpg)

@QuincyLarson I found this one inspirational for a start ;)

**Comment by kosta-xd** [comment]
And an alternate version with more varied font:

![fcc-quote itsalltalk 2](https://cloud.githubusercontent.com/assets/16733970/17852968/4b1adf96-686a-11e6-8890-635e76adba8c.jpg)

**Comment by QuincyLarson** [comment]
@kosta-xd Awesome! I've shared these with the core team to get an opinion :)

**Comment by QuincyLarson** [comment]
@kosta-xd The core team was definitely in favor of your first design. They were wondering what it would look like in Tron blue: ~[](https://i.ytimg.com/vi/o-SCNf7YwBA/maxresdefault.jpg)

**Comment by kosta-xd** [comment]
![fcc-quote itsalltalk](https://cloud.githubusercontent.com/assets/16733970/18078300/20aa5ecc-6e8b-11e6-82f8-41829e058f65.png)

@QuincyLarson looks cool, me thinks ;)

**Comment by QuincyLarson** [comment]
@kosta-xd Awesome! Yes - agreed! This looks beautiful. I will print these. Could you upload a high res blue-on-transparent png?

**Comment by kosta-xd** [comment]
@QuincyLarson Sure, but wouldn't it work better if I send you the SVG, my guess is the printer will appreciate it being a vector format rather than bitmap?

**Comment by QuincyLarson** [comment]
@kosta-xd yes - that sounds good. SVG should work fine :)
