### ISSUE TITLE
Stylized Quote: "When in doubt, use brute force." 

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#116]
Quote: "When in doubt, use brute force." 
Quotee: Ken Thompson

Requirements:
- vector graphic
- monochromatic
- iconography is OK
- dimensions should be 4:3

Here are some examples of relatively conventional typographic quotes you would see on t-shirts: 

![](http://assets.yellowtrace.com.au/wp-content/uploads/2013/05/Typography-Posters-of-Inspirational-Quotes-by-Ben-Fearnley-Yellowtrace-02.jpg)

![](http://cdn.shopify.com/s/files/1/0166/0736/products/Screen_Shot_2014-04-06_at_5.57.13_PM_large.png?v=1435811856)

**Comment by meetmangukiya** [comment]
[Stylised Quote: When in doubt, use brute force](https://github.com/meetmangukiya/assets/blob/dev/brute%20force%20attempt%201.svg)

**Comment by QuincyLarson** [comment]
@meetmangukiya this isn't bad. I was thinking it could fill up more of the allocated space and be more dramatic like this 

![](http://assets.yellowtrace.com.au/wp-content/uploads/2013/05/Typography-Posters-of-Inspirational-Quotes-by-Ben-Fearnley-Yellowtrace-02.jpg)

or this:

![](http://cdn.shopify.com/s/files/1/0166/0736/products/Screen_Shot_2014-04-06_at_5.57.13_PM_large.png?v=1435811856)

**Comment by meetmangukiya** [comment]
@QuincyLarson Let's see if I can make something like the above one. It seems out of my league at the moment :sweat_smile: , but I'll definitely try. And I'd also like to suggest you to add the examples in other issues of Stylized Quote too :+1:

**Comment by QuincyLarson** [comment]
@meetmangukiya good point. I will add these images to the other quote issues for reference. 

Thanks for giving this your best effort! :) We have lots of other designers who are contributing whom you can reach out to for expert feedback, such as @kosta-xd.

**Comment by kosta-xd** [comment]
@meetmangukiya has gotten some general advice from me in his Gitter inbox.

The second example provided by @QuincyLarson is quite a challenge even for a seasoned professional ;) But I get the point, of course, it's in adding rhythm and dynamic to a quote so it's not just a bunch of typed out words. It shouldn't rely on visuals either, other than a little support from decorative elements found in above examples.

**Comment by QuincyLarson** [comment]
@kosta-xd thank you for sharing your insights with @meetmangukiya :)

It's OK to use visuals, but I wouldn't go overboard with imagery. For example, this could show something like a fist, muscles, a battering ram, or something like that, but a majority of the image should be text.

**Comment by migben** [comment]
is this still open
