### ISSUE TITLE
Badge: Velociraptor Attack Survivor

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#117]
To earn: Attempt to solve a challenge more than 60 times.
Class: silver

**Comment by haydmills** [comment]
![velociraptor-badge](https://cloud.githubusercontent.com/assets/4451324/16929428/bd89cae0-4d05-11e6-8177-ea01c681f0a7.png)

Thoughts?

**Comment by atjonathan** [comment]
I love this.

**Comment by QuincyLarson** [comment]
This one looks great, too. Velociraptors had a slightly more pointed beak, which makes them look more sinister. Aside from the sharp teeth, this raptor looks almost friendly.

**Comment by haydmills** [comment]
Great insights! Thanks for the feedback. I will make some changes to it and upload a few different designs later to get more feedback. Looking at it now I am also not a huge fan of the colors. I'm still struggling with color palettes and which ones to use for which designs. I'm trying to learn though and make changes based on new things I read about color theory :)

**Comment by QuincyLarson** [comment]
@haydmills OK - keep tinkering. Thanks for keeping me posted on this. Let me know if there is anything I can do to keep you un-blocked :)

**Comment by haydmills** [comment]
![velociraptor-2](https://cloud.githubusercontent.com/assets/4451324/17081402/d2e23292-5124-11e6-92cc-c06cd909e15d.png)

**Comment by migben** [comment]
@QuincyLarson is this still open?
