### ISSUE TITLE
Badge: Shark Attack Survivor

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#118]
To earn: Attempt to solve a challenge more than 100 times.
Class: gold

**Comment by haydmills** [comment]
![shark-badge](https://cloud.githubusercontent.com/assets/4451324/16929413/ae7fcf72-4d05-11e6-92bf-d23f7479700f.png)

Thoughts?

**Comment by atjonathan** [comment]
Wow these are awesome :tada:

**Comment by haydmills** [comment]
@atjonathan thank you!

**Comment by QuincyLarson** [comment]
@haydmills so you think we should mix shapes? This is certainly an option, though if we want to print physical copies of these as stickers or iron-on patches in the future, they would need to be dye-cut as opposed to round (which would increase cost). 
I noticed with traditional boy scout badges, they are all round. 
![](https://upload.wikimedia.org/wikipedia/en/a/a8/Merit_badge_sash.png)

This isn't a limitation for virtual assets, but it would be for physical versions.

**Comment by haydmills** [comment]
Yes good point. I was more designing for digital but I can make them all one consistent shape due to them living both in digital and print.

**Comment by haydmills** [comment]
![shark-2](https://cloud.githubusercontent.com/assets/4451324/17081413/915b384a-5125-11e6-81d3-8ee14ae5d1c6.png)

**Comment by QuincyLarson** [comment]
@haydmills I dig it! Much more in line with what I was thinking (not that my thinking is optimal) but it looks great to me!
