### ISSUE TITLE
Badge: Rabbit of Caerbannog attack Survivor

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#119]
To earn: Attempt to solve a challenge more than 200 times.
Class: platinum

**Comment by haydmills** [comment]
![rabbit-of-caerbannog](https://cloud.githubusercontent.com/assets/4451324/16933860/4cd90404-4d1f-11e6-9620-5e36c47f45dd.png)

Thoughts?

**Comment by haydmills** [comment]
![rabbit-of-caerbannog](https://cloud.githubusercontent.com/assets/4451324/16933886/7837c6bc-4d1f-11e6-9847-fa6a59bbc690.png)

Thoughts?

**Comment by haydmills** [comment]
![rabbit-of-caerbannog](https://cloud.githubusercontent.com/assets/4451324/16933905/bc36e69a-4d1f-11e6-8a95-c928d8686697.png)

Thoughts?

**Comment by atjonathan** [comment]
I also love this :heart:

**Comment by QuincyLarson** [comment]
@haydmills wow - this looks great! You even got the text on there! Though it is a bit low contrast white on yellow. Would adding some sort of small border around it using one of the existing colors (such as the orange you used for the border) make it more legible? Did you use Lato? Should we use all upper case for these?

**Comment by haydmills** [comment]
Thanks Quincy! Yeah I agree it needs tweaked some more. For all three badges I have used Lato for the font. Personally, I think uppercase works better for the badges but I can upload some different variations to get more feedback. I will also add some badge designs without text!

**Comment by QuincyLarson** [comment]
@haydmills OK - sounds great. We are using SaxMono for Free Code Camp's logo - I wonder how a monospace font with all lowercase might look.

**Comment by haydmills** [comment]
![rabbitt-2](https://cloud.githubusercontent.com/assets/4451324/17081401/ba573d26-5124-11e6-91d9-82af14960c1a.png)

**Comment by QuincyLarson** [comment]
Oh man. That rabit looks even more menacing on a red background! Excellent work!

**Comment by migben** [comment]
is this still open?
