### ISSUE TITLE
T-shirt design: Open data

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/assets#120]
As advocates for open data, we would like to print a t-shirt that visualizes the concept of open data in a compelling way.

Requirements:
- vector graphic
- monochromatic
- iconography is OK
- dimensions should be 4:3

**Comment by kosta-xd** [comment]
![fcc-shirt](https://cloud.githubusercontent.com/assets/16733970/17648582/3f340eaa-621b-11e6-98df-e1c0c9d81f2a.jpg)

Based on Open Data sticker.

**Comment by atjonathan** [comment]
That looks awesome @kosta-xd :tada:

**Comment by kosta-xd** [comment]
@atjonathan thank you!! As mentioned by @QuincyLarson for the sticker, I need to switch the capital O to a small one.

**Comment by QuincyLarson** [comment]
@kosta-xd Also, could you remove the semicolon? Most languages have () but many of them (like Python and R - which are popular languages for data science) do not require terminating semicolons.

**Comment by kosta-xd** [comment]
Sure thing @QuincyLarson Any other specific feedback from the team?

**Comment by QuincyLarson** [comment]
@kosta-xd my other feedback would be to make the cylinder segments thicker, and the gaps between them thinner. If you look at most data drums, the gaps are quite small.

**Comment by kosta-xd** [comment]
@QuincyLarson No probs, will do.

**Comment by kosta-xd** [comment]
![fcc-shirt-opendata](https://cloud.githubusercontent.com/assets/16733970/17657753/2eafec2e-62c6-11e6-9893-5b1d6db8293e.png)

@QuincyLarson Done! ;) Will upload the update to sticker topic as well.
