### ISSUE TITLE
Finalize Style Guide

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#123]
@haydmills could you add a checklist of tasks that remain before we ship the style guide?

Live styleguide: https://haydmills.github.io/

**Comment by haydmills** [comment]
Checklist:
- [ ] Finalize color palette 
- [ ] Add SVG logo downloads
- [ ] Add example section with use cases for logo and color palette (i.e FCC t-shirts, stickers, badges, website uses, etc)

**Comment by haydmills** [comment]
![all-together](https://cloud.githubusercontent.com/assets/4451324/17081421/e1191e24-5125-11e6-895c-fa2e1ae7afb3.png)

**Comment by atjonathan** [comment]
Any update on this @haydmills ?
