### ISSUE TITLE
Future Coder Onesie design for babies

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/assets#124]
@haydmills

You may have seen the "future doctor" or "future lawyer" onesies for babies. We want to create "future coder" onesies for campers and their toddlers.

Here's what TeeSpring allows in terms of dimensions:

![](https://www.evernote.com/l/Ar_EfOxPgk9LGoF4f2bPSbkzj9V5BdK2xp0B/image.png)

I think we could use the FCC font, with the "bonfire function call" symbol. What do you think?

**Comment by haydmills** [comment]
![fcc-baby-onesies](https://cloud.githubusercontent.com/assets/4451324/17353635/62cedfa8-590f-11e6-9ca3-fe12e3e43fdb.png)

Here are a few simple designs with variations of the FCC font style. Let me know your thoughts @QuincyLarson!

**Comment by QuincyLarson** [comment]
@haydmills Awesome! I'm sharing with the core team and showing my wife.

**Comment by QuincyLarson** [comment]
@haydmills all the feedback has been in favor of lowercase. I think we have a winner.

One person was curious what it would look like with the text a bit lower.

**Comment by haydmills** [comment]
![future-coder-onesie](https://cloud.githubusercontent.com/assets/4451324/17364038/d46ace74-594b-11e6-828d-b80482bdec0e.png) 

Here is the PNG file of the lowercase style that should be easy to drag and drop onto Teespring when you are actually creating the onesie.

**Comment by QuincyLarson** [comment]
Thanks to @haydmills' efforts, this is now live and campers are getting these for their babies: https://teespring.com/future-coder-baby-onesies#pid=287&cid=6090&sid=front
