### ISSUE TITLE
Graphics: "Code Grant" social media icon, banner image

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/assets#127]
Free Code Camp completes pro bono code for nonprofits by issuing Code Grants. We need graphical assets to support this program.

**Comment by kosta-xd** [comment]
Hi @CodeNonprofit could you please provide some more details on these? What's the required content, sizes, etc.

**Comment by CodeNonprofit** [comment]
Thanks @kosta-xd - I'm looking for a basic design that includes the copy 'Code Grant' to be used for campaigns on social media and elsewhere. The standard icon size of 32x32 works for a square profile image. For banner, 300x250 or 728x90 would be perfect. It can be as simple as white text on a green background, but the point is to build a few assets to help us raise awareness of our program.

For context: Code Grants are awards given to nonprofits by Free Code Camp that represent upward of $50,000 in pro bono code. We have slim to no branding for it right now - only what you see at https://www.freecodecamp.com/nonprofits
