### ISSUE TITLE
Updated landing assets

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#130]
I love the icons @Rybar created nearly two years ago. They've been viewed millions of times. Since we redesigned FCC back in January, they seem a bit too ornate. 

Also, we are considering simplifying our landing page and our message. Here's what it might look like:

![](https://www.evernote.com/l/Ar_LwOaXtkVArKFdQp2ODRNABnbw8QuMs0EB/image.png)

Those icons are placeholders. I was wondering whether we could come up with three simple icons that are solid green on white that convey: learning to code, contributing to open source, and getting a job.

@Wes26 @kosta-xd would either of you be interested in attempting this?

**Comment by Annastaciahubbard** [comment]
Has this been done?

**Comment by atjonathan** [comment]
@Annastaciahubbard, no, not yet! Would you be interested in taking this up?

**Comment by QuincyLarson** [comment]
@Annastaciahubbard yes - we would welcome your contributions on this :)

**Comment by SUPERETDUPER** [comment]
This landing page seems to have been updated with new graphics. Should this issue be closed?

**Comment by QuincyLarson** [comment]
@SUPERETDUPER the landing page is still using the same assets we've been using for 2 years.

**Comment by SUPERETDUPER** [comment]
Sorry miss read the issue.
