### ISSUE TITLE
City campsite assets

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/assets#131]
Here's a list of campsites with more than 1,000 members:
- London 
- Delhi 
- Atlanta
- Chicago
- Seattle
- Bengaluru
- San Francisco
- New York City
- Toronto

My thinking is that we could create assets visually similar to our other stickers: white on green. 

@Wes26 has already created one that in my (non-designer) opinion looks like a good start:

![](https://cloud.githubusercontent.com/assets/16253583/17614549/76e86688-6091-11e6-95d9-f3b847c15dbb.png)

We could minimize the text by just saying "Free Code Camp" along the top, and then the city name on the bottom. The goal would be consistency and having a famous landmark (such as the Big Ben for London or the space needle for Seattle) as the illustration.

**Comment by groovyy** [comment]
I've created some possible designs for these assets (New York City to start). Let me know what you think. I'll be working on assets for the other cities next (London, Delhi, Atlanta, Chicago, Seattle, Bengaluru, San Francisco, Toronto.)


![freecodecamp - newyorkcity 6 versions-05](https://cloud.githubusercontent.com/assets/17690291/20641652/a9fbd06e-b3ca-11e6-882d-949b09d2e31b.png)
![nyc green and whie](https://cloud.githubusercontent.com/assets/17690291/20641717/2286b6f6-b3cc-11e6-9acd-ceaa0e0ddf9c.png)

**Comment by QuincyLarson** [comment]
@groovyy Wow - these look amazing! I am partial to the bottom large image, since it's a simple unshaded white on green is in keeping with our other stickers. 

One thing I would point out (and keep in mind that I'm a non-designer) is that some of the fine detail may not come out very well on a 2" sticker (such as the top of the Chrysler building and the little rectangles on the shoreline). You might want to eliminate these or figure out a way to achieve these with less detail.

I'm mentioning @Rybar, @Wes26, @kosta-xd and @hallaathrad to see if they can give you more educated feedback on these :)

**Comment by hallaathrad** [comment]
Those look great!! My concern would be how clear they'll come on the actual print size. The lines may be a tad too thin and the elements too detailed. Great illustrations, thought. It would've taken me days to come up with something this sophisticated :)

**Comment by groovyy** [comment]
Hey all,

Thank you for the feedback, I really appreciate it! I went back and edited the designs (removed the details and made the lines more uniform. Let me know what you guys think of the edits. 

@QuincyLarson @hallaathrad 
![image](https://cloud.githubusercontent.com/assets/17690291/20801158/e97025da-b7b5-11e6-84b8-6f42af5e1c0e.png)

**Comment by QuincyLarson** [comment]
@groovyy much better imho.

**Comment by gwenf** [comment]
@QuincyLarson Can we get the templates for these to update and use for our local group?

**Comment by QuincyLarson** [comment]
@groovyy Do you still have the files you used to create these graphics?
