### ISSUE TITLE
2016 be like... "I'm hacking everyone"

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/assets#132]
My idea is to create an asset that plays off the popular meme: 2016 be like "I'm taking everyone"

![](http://i1.kym-cdn.com/photos/images/original/001/152/053/cf7.png)

Instead of the faces, we could include corporate logos, with the number of accounts breached below. We could leave Harambe in there as the 6th breach as a nod to the meme, or we could include the lesser known (outside of Russia) VK.com

2016 be like... "I'm hacking everyone"

Yahoo 500,000,000
Myspace 360,000,000
Linkedin 160,000,000
Dropbox 68,000,000
Tumblr 65,000,000
VK 93,000,000

Steps:
- get the logos
- apply the meme font
- add some sort of Free Code Camp watermark (since if all goes well, it will be shared beyond our accounts)

Is anyone interested in helping build this asset?

**Comment by CodeNonprofit** [comment]
This is funny. But don't include Harambe. The memes aren't funny - and some are racist. RIP Harambe.

**Comment by Khiarov** [comment]
I'm on it!
I'll send it over on twitter.

**Comment by QuincyLarson** [comment]
@Khiarov thank you so much! I've published this on both Twitter and Facebook and may even include it on our Pinterest account if I can remember the password :)
