### ISSUE TITLE
Style guide alternative logo wrong colour underline.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/assets#148]
@Middi commented on [Tue Nov 07 2017](https://github.com/freeCodeCamp/freeCodeCamp/issues/16080)

#### Issue Description
Color of the underline of the fire portion of the logo for the alternative logo in png, jpeg and eps is white and should be green.

#### Screenshot
<img width="492" alt="screen shot 2017-11-07 at 15 16 34" src="https://user-images.githubusercontent.com/15717148/32501066-f28e1ae8-c3ce-11e7-9000-709be8787734.png">

#### Link
https://design-style-guide.freecodecamp.org

---

@Barkha54 commented on [Sun Nov 12 2017](https://github.com/freeCodeCamp/freeCodeCamp/issues/16080#issuecomment-343725159)

Hi, can you tell me where I will find this file? All the images seems to be hosted on Amazon AWS and I'm not able to find them on my local setup. I would like to take up this issue.

**Comment by migben** [comment]
is this still open?
